/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Emprestimo;

import Base.Util;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class Emprestimo extends javax.swing.JFrame {

    /**
     * Creates new form Emprestimo
     */
    public Emprestimo() {
        initComponents();
        Util.centralizar(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        LbDatempre = new javax.swing.JLabel();
        TxtDatempre = new javax.swing.JFormattedTextField();
        LbDateDevolu = new javax.swing.JLabel();
        TxtDevolu = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtCodCliente = new javax.swing.JTextField();
        LbNomeCli = new javax.swing.JLabel();
        TxtNomeClient = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtCodlivro = new javax.swing.JTextField();
        LbNomeLivro = new javax.swing.JLabel();
        TxtNomeLivro = new javax.swing.JTextField();
        LbDatPrev = new javax.swing.JLabel();
        TxTDataPrev = new javax.swing.JFormattedTextField();
        BtnDevolu = new javax.swing.JButton();
        BtnEmprestar = new javax.swing.JButton();
        LbInfEmp = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Empréstimo de Livros:");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LbDatempre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbDatempre.setText("Data do Empréstimo:");

        TxtDatempre.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        TxtDatempre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        LbDateDevolu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbDateDevolu.setText("Data de Devolução: ");

        TxtDevolu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        TxtDevolu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Código do Cliente:");
        jLabel1.setToolTipText("");

        TxtCodCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TxtCodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodClienteActionPerformed(evt);
            }
        });

        LbNomeCli.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbNomeCli.setText("Nome de Cliente:");

        TxtNomeClient.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Código do Livro:");

        TxtCodlivro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TxtCodlivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodlivroActionPerformed(evt);
            }
        });

        LbNomeLivro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbNomeLivro.setText("Nome do Livro:");

        TxtNomeLivro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(TxtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TxtCodlivro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtNomeClient)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbNomeLivro)
                            .addComponent(LbNomeCli))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(TxtNomeLivro))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LbNomeCli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNomeClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LbNomeLivro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCodlivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        LbDatPrev.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbDatPrev.setText("Data Prevista de Devolução:");

        TxTDataPrev.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        TxTDataPrev.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        BtnDevolu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnDevolu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/min_iconerefresh.png"))); // NOI18N
        BtnDevolu.setText("Devolução");

        BtnEmprestar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnEmprestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/min_iconeconfirmar.png"))); // NOI18N
        BtnEmprestar.setText("Emprestar");
        BtnEmprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEmprestarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbDatempre)
                    .addComponent(LbDateDevolu)
                    .addComponent(LbDatPrev))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TxtDevolu)
                    .addComponent(TxtDatempre, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxTDataPrev, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(BtnDevolu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnEmprestar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDatempre)
                    .addComponent(TxtDatempre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDatPrev)
                    .addComponent(TxTDataPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbDateDevolu)
                    .addComponent(TxtDevolu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDevolu)
                    .addComponent(BtnEmprestar)))
        );

        LbInfEmp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LbInfEmp.setText("Informações de Empréstimo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LbInfEmp)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LbInfEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodClienteActionPerformed

    private void BtnEmprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEmprestarActionPerformed
        // TODO add your handling code here:
        if(!validar()){
           return;
       }
       JOptionPane.showMessageDialog(this,"ok","ok",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_BtnEmprestarActionPerformed

    private void TxtCodlivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodlivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodlivroActionPerformed
     private boolean validar(){
     if(this.TxtDatempre.getText().isEmpty()){
         JOptionPane.showMessageDialog(this, "Data de Emprestimo e Obrigatorio", "Atenção", JOptionPane.WARNING_MESSAGE);
        return false;
     }
       if(this.TxtDevolu.getText().isEmpty()){
         JOptionPane.showMessageDialog(this, "Data de Devolução e Obrigatorio", "Atenção", JOptionPane.WARNING_MESSAGE);
        return false;
       }
     return true;
     }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDevolu;
    private javax.swing.JButton BtnEmprestar;
    private javax.swing.JLabel LbDatPrev;
    private javax.swing.JLabel LbDateDevolu;
    private javax.swing.JLabel LbDatempre;
    private javax.swing.JLabel LbInfEmp;
    private javax.swing.JLabel LbNomeCli;
    private javax.swing.JLabel LbNomeLivro;
    private javax.swing.JFormattedTextField TxTDataPrev;
    private javax.swing.JTextField TxtCodCliente;
    private javax.swing.JTextField TxtCodlivro;
    private javax.swing.JFormattedTextField TxtDatempre;
    private javax.swing.JFormattedTextField TxtDevolu;
    private javax.swing.JTextField TxtNomeClient;
    private javax.swing.JTextField TxtNomeLivro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
