
import Emprestimo.Emprestimo;
import Formularios.ListCliente;
import Formularios.ListLivro;
import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author marco
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LaImg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MePrincipal = new javax.swing.JMenu();
        Meemprestimo = new javax.swing.JMenuItem();
        ImSair = new javax.swing.JMenuItem();
        MeCadas = new javax.swing.JMenu();
        client = new javax.swing.JMenuItem();
        MeItenLivros = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.png"))); // NOI18N

        MePrincipal.setMnemonic('p');
        MePrincipal.setText("Principal");
        MePrincipal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Meemprestimo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Meemprestimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/min_iconerefresh.png"))); // NOI18N
        Meemprestimo.setText("Emprestimo");
        Meemprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeemprestimoActionPerformed(evt);
            }
        });
        MePrincipal.add(Meemprestimo);

        ImSair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ImSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/min_iconedeletar.png"))); // NOI18N
        ImSair.setText("Sair");
        ImSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair(evt);
            }
        });
        MePrincipal.add(ImSair);

        jMenuBar1.add(MePrincipal);

        MeCadas.setMnemonic('c');
        MeCadas.setText("Cadastros ");
        MeCadas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        client.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        client.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/download_1.png"))); // NOI18N
        client.setText("Clientes");
        client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarClientes(evt);
            }
        });
        MeCadas.add(client);

        MeItenLivros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MeItenLivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2921302.png"))); // NOI18N
        MeItenLivros.setText("Livros");
        MeItenLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeItenLivrosActionPerformed(evt);
            }
        });
        MeCadas.add(MeItenLivros);

        jMenuBar1.add(MeCadas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(LaImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LaImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // METODO EXECUTADO PELO BOTÃO SAIR 
    private void sair(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sair
    private void LaImg(java.awt.event.ActionEvent evt) {
        Inicio a = new Inicio();
        a.setVisible(true);
        Toolkit tool = Toolkit.getDefaultToolkit();
        Dimension tamanho = tool.getScreenSize();
        a.setSize(tamanho);
    }
    private void listarClientes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarClientes
        // TODO add your handling code here:
        new ListCliente().show();
    }//GEN-LAST:event_listarClientes

    private void MeItenLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeItenLivrosActionPerformed
        // TODO add your handling code here:
         new ListLivro().show();
    }//GEN-LAST:event_MeItenLivrosActionPerformed

    private void MeemprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeemprestimoActionPerformed
        // TODO add your handling code here:
        new Emprestimo().show();
    }//GEN-LAST:event_MeemprestimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Inicio i = new Inicio();
                i.setVisible(true);

                Toolkit tool = Toolkit.getDefaultToolkit();
                Dimension tamanho = tool.getScreenSize();
                i.setSize(tamanho);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ImSair;
    private javax.swing.JLabel LaImg;
    private javax.swing.JMenu MeCadas;
    private javax.swing.JMenuItem MeItenLivros;
    private javax.swing.JMenu MePrincipal;
    private javax.swing.JMenuItem Meemprestimo;
    private javax.swing.JMenuItem client;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
